-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 12:42:43 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starbucks
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `starbucks` ;

-- -----------------------------------------------------
-- Schema starbucks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starbucks` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `starbucks` ;

-- -----------------------------------------------------
-- Table `starbucks`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`manager` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`manager` (
  `manager_id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`manager_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`warehouse` (
  `warehouse_id` INT NOT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`warehouse_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`store` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`store` (
  `store_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `store_name` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `manager_manager_id` INT NOT NULL COMMENT '',
  `warehouse_warehouse_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`store_id`, `manager_manager_id`, `warehouse_warehouse_id`)  COMMENT '',
  INDEX `fk_store_manager_idx` (`manager_manager_id` ASC)  COMMENT '',
  INDEX `fk_store_warehouse1_idx` (`warehouse_warehouse_id` ASC)  COMMENT '',
  CONSTRAINT `fk_store_manager`
    FOREIGN KEY (`manager_manager_id`)
    REFERENCES `starbucks`.`manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_warehouse1`
    FOREIGN KEY (`warehouse_warehouse_id`)
    REFERENCES `starbucks`.`warehouse` (`warehouse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`barista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`barista` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`barista` (
  `barista_id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `salary` INT NULL COMMENT '',
  `store_store_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`barista_id`, `store_store_id`)  COMMENT '',
  INDEX `fk_barista_store1_idx` (`store_store_id` ASC)  COMMENT '',
  CONSTRAINT `fk_barista_store1`
    FOREIGN KEY (`store_store_id`)
    REFERENCES `starbucks`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`customer` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`customer` (
  `customer_id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`customer_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`receipt` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`receipt` (
  `receipt_id` INT NOT NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  `store_store_id` INT NOT NULL COMMENT '',
  `customer_customer_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`receipt_id`, `store_store_id`, `customer_customer_id`)  COMMENT '',
  INDEX `fk_receipt_store1_idx` (`store_store_id` ASC)  COMMENT '',
  INDEX `fk_receipt_customer1_idx` (`customer_customer_id` ASC)  COMMENT '',
  CONSTRAINT `fk_receipt_store1`
    FOREIGN KEY (`store_store_id`)
    REFERENCES `starbucks`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `starbucks`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`product` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`product` (
  `product_id` INT NOT NULL COMMENT '',
  `product_name` VARCHAR(45) NULL COMMENT '',
  `price` INT NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`receipt_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`receipt_detail` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`receipt_detail` (
  `product_product_id` INT NOT NULL COMMENT '',
  `receipt_receipt_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`product_product_id`, `receipt_receipt_id`)  COMMENT '',
  INDEX `fk_receipt_detail_receipt1_idx` (`receipt_receipt_id` ASC)  COMMENT '',
  CONSTRAINT `fk_receipt_detail_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_detail_receipt1`
    FOREIGN KEY (`receipt_receipt_id`)
    REFERENCES `starbucks`.`receipt` (`receipt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`panini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`panini` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`panini` (
  `product_product_id` INT NOT NULL COMMENT '',
  `salt` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_panini_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`cake`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`cake` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`cake` (
  `product_product_id` INT NOT NULL COMMENT '',
  `pastry` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_cake_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`coffee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`coffee` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`coffee` (
  `product_product_id` INT NOT NULL COMMENT '',
  `caffeine` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_coffee_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`tea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`tea` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`tea` (
  `product_product_id` INT NOT NULL COMMENT '',
  `leaf` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_tea_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`cup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`cup` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`cup` (
  `product_product_id` INT NOT NULL COMMENT '',
  `porcelaine` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_cup_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starbucks`.`trumbler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `starbucks`.`trumbler` ;

CREATE TABLE IF NOT EXISTS `starbucks`.`trumbler` (
  `product_product_id` INT NOT NULL COMMENT '',
  `titanium` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`product_product_id`)  COMMENT '',
  CONSTRAINT `fk_trumbler_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `starbucks`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
